---
title: "Vinculación de la Ciencia"
author: ""
date: ""
output: html_document
---

Tengo larga y documentada experiencia en vinculación del conocimiento científico. Desde hace mucho años he participado en foros dedicados a la restauración como el [Pacto por la Restauración del Bosque Atlántico](https://www.pactomataatlantica.org.br/) y la [Plataforma Brasileña de Biodiversidad y Servicios Ecosistémicos](https://www.bpbes.net.br/). Para el primer, estoy actualmente coordinando un taller para el monitoreo participativo de la restauración y para el segundo, fui coautor de un reporte nacional sobre restauración además de ser miembro del consejo técnico-científico. También suelo escribir textos para revistas de divulgación y sitios web siempre es necesario, para llevar la información a grupos no académicos, como organizaciones gubernamentales y no gubernamentales dedicadas a la restauración. He coordinado campañas de creación de áreas protegidas en Brasil, que han demandado toda suerte de habilidades de comunicación social, resultando el [la creación de un área protegida de 110 mil hectáreas](https://www.youtube.com/watch?v=rQHAgyrXims) dedicada al Armadillo endémico del bosque seco de Brasil y que fue mascota del mundial de fútbol de 2014 en Brasil. Esta experiencia también la quiero compartir con el personal académico y discente del CICY y tendré enorme satisfacción en ingresar a los grupos de trabajo que auxilien el diseño de políticas públicas en México. Por fin, tengo intención en participar activamente en la difusión del conocimiento generado por el CICY, creando material diverso y moderno de vinculación además de entrenar estudiantes para la comunicación social con foco en la restauración y conservación de la biodiversidad de las Selvas Mayas.


Concluyo afirmando que sería un gran honor y una maravillosa oportunidad establecer nuevos retos científicos, personales y académicos en México y tener la oportunidad de desarrollar nuevas habilidades en el ambiente colaborativo y de excelencia del CICY. La institución podrá contar con un investigador con experiencia y productividad suficiente para pertenecer al Sistema Nacional de Investigadores, al menos con nivel II en la primera convocatoria. Así, aunque parezca sobrecalificado para la plaza, estoy seguro que muy prontamente pueda ascender al nivel de titular que me corresponda por mi productividad. Mi propuesta es compartir con el plantel del CICY toda mi experiencia académica y la red de cooperación que establecí tras años de trabajo consistente. Volver a vivir y trabajar en México es más que una oportunidad, es la realización de un proyecto de vida.


<iframe width="1186" height="667" src="https://www.youtube.com/embed/rQHAgyrXims" title="O gol do Tatu-bola (The armadillo's goal)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
